### PR TITLE
home: add 'eosDAC Partner' section

### PR DESCRIPTION
**Pull request by slyon**
Haiying Yang requested a "Partner" section on the homepage (via Discord #meeting-room-chat1). I'm putting this up for discussion via this pull request.

This is how it would look like:
partner

### CODE REVIEW

**Comment by lukestokes** [comment]
Would this be focused on exchanges or organizations that want to use DAC technology? Or this a separate thing from what we're doing here? https://eosdac.io/enabling-dacs/

I was thinking we create a partner page focusing on those who are using our technology and we highlight how those communities are encouraged to airdrop on active eosDAC members.

Maybe we can include exchanges as well?

Also, maybe we should list exchanges on our tools page after the DAC Token section. They are tools, in a sense, for creating token liquidity.

edit: oh, also, for the partner stuff, we should link to it from the "Why Launch a DAC?" page and the partner page should link back to that page.

**Comment by slyon** [comment]
Actually, I'm not sure what content Haiying Yang wanted to have in there. He suggested the TokenPocket app on Discord.

Overall, this section is separate from "Enabling DACs" (here on the staging server: http://eosdac.slyon.de/success-stories ), but sure the content could be merged.

**Comment by yhaiying** [comment]
@lukestokes @slyon I'am Haiying Yang. Responded to your question in discord #eosdac-main

**Comment by slyon** [comment]
we now have a exchange section at https://beta.eosdac.io/tools/ and a "How to vote with TokenPoket" video will soon be published here: https://beta.eosdac.io/how-to-vote/

So, I'm going to close this PR (withour merging).

**Pull request closed without merging**
