### PR TITLE
Added exchanges and token information to tools page.

### PR DESCRIPTION
**Pull request by paplooo**

### CODE REVIEW

**Comment by slyon** [comment]
Great work, I like it!

**Comment by lukestokes** [comment]
Looks great!
image
I wonder if we need each exchange as a separate file, but I guess that's okay. I'll go ahead and merge it in.

**Comment by paplooo** [comment]
@lukestokes I was wondering the same. To be honest I wasn't feeling very good about adding it like that. I was hoping to do something like we did for our social media icons on the footer, I spent a lot of time trying to figure how to do that with markdown includes for images, then I gave up. Maybe @slyon can help us to optimize that, I am not sure whether having a separate file for each exchange increases the load time.

**Comment by lukestokes** [comment]
No concern with load time as it all gets compiled together when the site is built, I think.

**Comment by slyon** [comment]
The markdown files will not increase the load time. They are compiled together, as Luke said.

And having 1 .md file per exchange is actually the best was I can imagine for having (HTML)-code and content (image + name of exchange) separated. Unfortunately it is not possible to build CSS grids directly in markdown.

The only other option might be a markdown table, but this will not conform to the responsive design and will not look good on mobile (small screen) browsers.

**Comment by paplooo** [comment]
@slyon 
Thanks for clearing this.

**Pull request merged**
