### PR TITLE
Lynx support

### PR DESCRIPTION
**Pull request by slyon**
adopt the button to "Vote using EOS Lynx"

### CODE REVIEW

**Comment by slyon** [comment]
I've updated this PR to detect accounts which are not contained in the 'eosio.voters' table and thus having account.voter_info = null. Such accounts have never voted before => we cast a vote for just 'eosdacserver' in this case.

**Comment by slyon** [comment]
There seems to be a bug inside EOS Lynx (it does not recognize "............." as a valid, empty username – which it should be according to block.one)
https://github.com/EOSIO/eosjs/issues/533

I think we cannot fix this on our end...

**Comment by lukestokes** [comment]
@slyon based on the latest testing on the new version of EOS Lynx that worked, is this now ready to go?

**Comment by slyon** [comment]
@lukestokes If it works for you on iOS, its ready to be merged! Everything else has been tested to be working.

**Comment by lukestokes** [comment]
Fantastic!

**Pull request merged**
