### PR TITLE
added new pending steemit post

### PR DESCRIPTION
**Pull request by paplooo**
-The DAC Factory
-eosDAC invites you to EOS Alliance Chinese Community Meeting featuring Michael Yeates
-eosDAC reports active worker proposals, revenue and expenditure for December and January
-eosDAC DACTIVATION DAY is Here! (Feb 11th 2019)

### CODE REVIEW

**Comment by slyon** [comment]
I see all new posts starting with a filename of "2018-11-10-..." maybe you should rename those to better reflect the real date of the post, so it is easier to find those posts in the future.

**Comment by piecesnbits** [comment]
what about fetching the posts pragmatically instead of hardcoding them? if you have the link you can fetch the content.

**Comment by piecesnbits** [comment]
or even better use the steemit api to get the posts content.

**Comment by slyon** [comment]
how would we handle translations in this case? Lots of steemit posts do not have a translated version.

Right now the primary posts are fetched semi-automatically (using the nodeJS script from `scripts/fetch-steem`) and can then be translated (at least the title & abstract). In addition to that we always fetch the latest social media posts from Steemit, Youtube & Twitter into the 3 small boxes at the very top of the "News" page automatically via the Steem/Youtube/Twitter embeds.

**Comment by piecesnbits** [comment]
you could simply add a new translated steempost. this way the translation is also available on steem and will have a bigger audience.

**Comment by slyon** [comment]
Yes, that would be an option. But we would somehow need an "universal content scraper", as we do not only have steemit articles and would need support for all sorts of news, like:

- self-hosted PDF: https://eosdac.io/2019/02/20/financial-report2.html
- Youtube: https://eosdac.io/2018/07/31/token-explorer.html
- CoinDesk: https://eosdac.io/2018/04/25/eos-eyes-new-all-time-high-amid-positive-news-flow.html
- Medium: https://eosdac.io/2018/03/07/bios-boot-eosio-blockchain.html
- Mailchimp: https://eosdac.io/2018/04/19/airdrop.html

Or we need to get rid of all the history (legacy articles) and work with Steemit exclusively.... Not sure if this is a feasible solution.

**Comment by paplooo** [comment]
@slyon 
I added a couple more post and changed the file name with the post date for the ones I committed yesterday.

**Comment by slyon** [comment]
looks good to me. Merged.
@piecesnbits let's discuss the possible auto-fetching of news in discord!

**Pull request merged**
