### PR TITLE
Vietnamese - update Community, Token, How to Vote, fix some bugs

### PR DESCRIPTION
**Pull request by eosdacvietnam**

### CODE REVIEW

**Comment by lukestokes** [comment]
I noticed a lot of these are in English. I think it may be better to leave them out of the vi folder if they are just going to be english since their absence should just pull in the english version anyway. Once they are translated, putting them in the vi folder makes sense to me.

**Comment by eosdacvietnam** [comment]
Dear Luke, thanks for your comment. Actually, those long contents that haven't been translated yet are old posts linking to steemit. I intend to cut them shorter before translating because they are navigated to steemit posts and the news page only shows small part of the posts. Other commits are for fully translated and I think these are important :)

**Comment by lukestokes** [comment]
I guess my point is that translations shouldn't have any English in them. We talked about only bringing over translated files to the separate language folder. So my suggestion would be to go ahead and remove these English files from this pull request as they are currently no different than what is in the english folder, correct? Unless I'm missing something...

**Comment by eosdacvietnam** [comment]
I got it. Totally agree with you. I will pull requests with translated files. Those haven't been translated yet is gonna be done today. I will notice you when finished in order to merge :)

**Comment by eosdacvietnam** [comment]
Dear Luke, please check my commits. I get it all translated.
Update header:why-vote: connect scatter-vote buttons.
Thanks!

**Comment by eosdacvietnam** [comment]
Full updated and fix some word errors :)

**Comment by lukestokes** [comment]
Thanks!

**Pull request merged**
