### PR TITLE
As requested by Travis, removing cannabis.club

### PR DESCRIPTION
**Pull request by lukestokes**

### CODE REVIEW

**Comment by slyon** [comment]
@lukestokes Do we also need to remove this from @paplooo s new Community/Partners page?

**Comment by lukestokes** [comment]
@slyon I don't see the URL anywhere else other than translated files, so it should be fine.

image

**Comment by slyon** [comment]
Right, the partner section only links to: https://beehivebuds.co/

**Comment by slyon** [comment]
Merged. Thanks!

**Pull request merged**
